### PR TITLE
PlayerInfoPacket and chunk rendering improvements

### PR DESCRIPTION
**Pull request by djgaven588**
The goal of my changes is to both improve chunk rendering (handling how generation is done to how they are displayed), and handle the PlayerInfoPacket.

Changes so far:
- Added the handling of PlayerInfoPacket and EntityMetadata, metadata is not currently being used though.
- Updated Unity to 2019.1.14f1, sticking with 2019.1 but getting it up to date.
- Added Text Mesh Pro essentials
- PlayerLibrary is now populated
- Player list now is fully functional
- Started poking around with the chunk rendering

More details will be added as this is added to.

### CODE REVIEW

**Comment by Technoguyfication** [comment]
Hey, I took a quick look at your code and I'd recommend studying how packets are currently being handled. I see you reimplemented VarInt handling and you're using a `BinaryStream` for reading the packet. All the tools needed for parsing the packet body are available in the `PacketHelper` class. We also want to keep all business logic outside of the Packet class. It should only be used as a method of transporting data between the socket and GameManager (think of models in a MVC application).

At some point in the future the packet handling logic will need to be moved out of the Game Manager (and into World, Player, etc. possibly) but it should be put in there for now.

Thanks for the contribution by the way!

**Comment by djgaven588** [comment]
I am using BinaryReader for this code, as it is pretty much built for this kind of setup. I did however move all of the actual reading of the streams to a new class called "PacketReader" which has utility functions for reading it. Reading the protocol for [this packet](https://wiki.vg/Protocol#Player_Info), it seems to be a very complex packet, which requires a large amount of code to convert to a usable form in comparison to something like ChunkDataPacket. Unless I am completely missing something, the way I have implemented it so far seems fine. (I could be wrong, but I would assume from the available code I have to read that a SomethingPacket converts the data into what the protocol page displays)

**Comment by djgaven588** [comment]
For the above commit. Chat history and player list

**Comment by djgaven588** [comment]
We are ready for a merge over here. Let me know if I need to do any last minute changes. This is tested, and I have not had issues with it.

**Comment by Technoguyfication** [comment]
Quick question before I take a look at the code. Why did you add TextMeshPro twice? It was already in Assets/TextMeshPro

**Comment by djgaven588** [comment]
I don't see that for some reason, there is only _Project and Dependencies in my project's asset folder.

**Comment by djgaven588** [comment]
Reading the gitignore file, the folder you are talking about is completely ignored.

**Comment by Technoguyfication** [comment]
Ah you're right. It seems like this was a mistake in the gitignore when I created this project: https://github.com/github/gitignore/pull/3134

Should be fixed in master

**Comment by djgaven588** [comment]
Branches should now be mergable again. Unknown if all of your changes persisted.

**Review by Technoguyfication — CHANGES_REQUESTED** [review]
Okay. I did a code review and have a few things before merging:

- Please use `PascalCase` for public members and properties, as well as `_underscoredCamelCase` for private members
- Don't use long constructors for initialization of classes, instead, please use object initialization. ex:
```csharp
// don't do this
new Player(true, "mcplayer", Texture, 0x87, GameMode.Survival, 225, "mcplayer");

// instead, do this
new Player()
{
    HasDisplayName = true,
    DisplayName = "mcplayer",
    // etc., etc..
};
```

- However, it's okay to use long constructors with `struct`s because they should stay immutable, maybe we can refactor those to classes at a later time

(sorry for being such a nazi about code styling, i keep VS's messages enabled to enforce it on my projects)



- For now, please use a `List<byte>` and `PacketHelper` for deserialization of packets. I totally understand using a `ByteReader` is faster and more correct, but it will help keep all the code in one place for the time being

- Consider moving any code that deals with parsing non-primitives into their own classes. For example `ReadRotation` and `ReadParticle` should probably be in `EntityRotation` and `Particle` as constructors that take an arbitrary stream or collection of bytes

- `Particle.cs` shouldn't be under Protocol. Let's maybe put it under Entity for now.

- In the `ParticleType` enum the values use snake_case when they should use PascalCase. I know I'm a hypocrite because I'm using UPPERCASE_SNAKE_CASE in my other enums, but that's incorrect and I need to fix those as well - that's on me though. don't worry about the existing code. (I'm only seeing this instance of this, it may be in other parts of the code)

- I'm not totally sure what the `Position` struct is implementing that doesn't exist already. It looks like it's just integer so I feel like it could be replaced with `BlockPos`. Correct me if I'm wrong.

- Don't worry about the `regenerateNearbye` (sic) parameter in the ChunkRenderer. I'm planning on using combined bitfields and 3D chunk neighbor "dirtying" so chunk sections only regenerate the 5-6 chunk sections immediately adjacent to them.

- I noticed you love using `Queue<T>` and the `out` modifier. Unless you're returning multiple values (which even then a `Tuple` would probably be appropriate), please just use normal `return`. It improves readability. As for Queues, List<T> is slightly faster I believe.

That's all I've looked at for now. Super sorry about the laundry list of feedback, and I wouldn't normally be opposed to just merging and making the changes myself, but I'm about to head out for a while and don't have the time to make any corrections.

**Comment by djgaven588** [comment]
Position is separate, for it is a type [in the Protocol](https://wiki.vg/Protocol#Data_types), and I believe it is different from a BlockPos.

**Review by djgaven588 — COMMENTED** [review]
Went over the request, should be all good now. Highly recommended to go back over the changes, as most if not all the files that needed changes should have them.

**Review by Technoguyfication — APPROVED** [review]

**Comment by Technoguyfication** [comment]
merged changes

**Pull request closed without merging**
